### ISSUE TITLE
Exception when starting up plugin

### ISSUE THREAD

**Issue by knw257** [spdermn02/TouchPortal_Corsair_iCue#5]
I'm getting an exception I can't quite figure out how to fix when I try to start the iCUE plugin in TouchPortal. Here's the relevant info:

TouchPortal version: 3.6 build 6
TP iCUE plugin version: 1003
iCUE version: 4.29.203

Here's the content from the TouchPortal log:

01:48:00.512 - [LOG] (Plugin System) Executing plugin service: "C:\Users\{username}\AppData\Roaming\TouchPortal\plugins\TPCorsairiCue\touchportal_icue.exe"
01:48:00.602 - [ERROR] (Plugin Instance) pkg/prelude/bootstrap.js:1740
01:48:00.603 - [ERROR] (Plugin Instance)       throw error;
01:48:00.603 - [ERROR] (Plugin Instance)       ^
01:48:00.603 - [ERROR] (Plugin Instance) 
01:48:00.603 - [ERROR] (Plugin Instance) Error: The specified module could not be found.
01:48:00.603 - [ERROR] (Plugin Instance) 
01:48:00.603 - [ERROR] (Plugin Instance) C:\Users\{username}\AppData\Local\Temp\pkg\059dd76495eb4e437405a72093d92c03d8f4068292858cdcbd93e874458baedb\cue-sdk\prebuilds\win32-x64\node.napi.node
01:48:00.604 - [ERROR] (Plugin Instance)     at process.dlopen (pkg/prelude/bootstrap.js:2114:28)
01:48:00.604 - [ERROR] (Plugin Instance)     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
01:48:00.604 - [ERROR] (Plugin Instance)     at Module.load (internal/modules/cjs/loader.js:863:32)
01:48:00.604 - [ERROR] (Plugin Instance)     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
01:48:00.605 - [ERROR] (Plugin Instance)     at Module.require (internal/modules/cjs/loader.js:887:19)
01:48:00.605 - [ERROR] (Plugin Instance)     at Module.require (pkg/prelude/bootstrap.js:1719:31)
01:48:00.605 - [ERROR] (Plugin Instance)     at require (internal/modules/cjs/helpers.js:74:18)
01:48:00.605 - [ERROR] (Plugin Instance)     at load (C:\snapshot\TouchPortal_Corsair_iCue\node_modules\node-gyp-build\index.js:21:10)
01:48:00.606 - [ERROR] (Plugin Instance)     at Object.<anonymous> (C:\snapshot\TouchPortal_Corsair_iCue\node_modules\cue-sdk\index.js:1:104)
01:48:00.606 - [ERROR] (Plugin Instance)     at Module._compile (pkg/prelude/bootstrap.js:1794:22)

The path it's checking does exist, but is empty. The file it's looking for, node.napi.node, already exists in the plugin directory, C:\Users\{username}\AppData\Roaming\TouchPortal\plugins\TPCorsairiCue. As such, I'm not sure why it's looking for the file elsewhere, since it's already in the same directory as the executable

**Comment by knw257** [comment]
Figured it out - I deleted the temp folder and re-ran the executable and it seemed to work
